name: Build Playwright CRX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - run: npm run test:install
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test
      - uses: actions/upload-artifact@v3
        with:
          name: recorder-crx
          path: |
            examples/recorder-crx/dist/
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: pwbot-crx
          path: |
            examples/pwbot-crx/dist/
          retention-days: 5
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            tests/playwright-report/
            tests/test-results/
          retention-days: 5
